### ISSUE TITLE
完善域名列表去重

### ISSUE THREAD

**Issue by IceCodeNew** [Loyalsoldier/domain-list-custom#1]
举例来说：
https://github.com/Loyalsoldier/domain-list-custom/blob/cc256056dc147f02c337e94cac36d4d4eb92702f/cn.txt#L1340
已经包括以下域名：
https://github.com/Loyalsoldier/domain-list-custom/blob/cc256056dc147f02c337e94cac36d4d4eb92702f/cn.txt#L2279-L2287

**Comment by Loyalsoldier** [comment]
对于附带 @attr 的域名，都不去重。
