### ISSUE TITLE
apple和google站点采用full匹配问题

### ISSUE THREAD

**Issue by Jan20th9e** [Loyalsoldier/domain-list-custom#33]
发现本项目将上游这两个列表都采用了full匹配，而上游原本是使用domain匹配的。
现在发现一些问题，比如a100.phobos.apple.com这个域名，原本会被直连apple列表的phobos.apple.com这个域名匹配到，但是因为本项目采用full匹配所以会漏掉此类域名，然后可能被geolocation-!cn里的domain:apple.com匹配到然后走远程解析了，这只是举例之一的域名，现实可能会有诸如此类的大量后缀域名没被匹配到。
有个疑问是上游这两个列表应该是采用后缀域名的手法抓出来的，但是在本项目中则被用于full匹配，是否会失去这两个列表存在的意义。

**Comment by Jan20th9e** [comment]
这个问题就算使用加强版geosite使用apple-cn采用直连也会因为full匹配漏掉那些域名。
https://github.com/IrineSistiana/mosdns-cn/issues/18

**Comment by Loyalsoldier** [comment]
解释过了：https://github.com/Loyalsoldier/v2ray-rules-dat/issues/163

**Comment by Jan20th9e** [comment]
是否可以考虑增加一个轻量版geosite，类似黑白名单的， 将domain-china，apple-cn ，google-cn这三个列表归类为geosite:cn ，然后将gfwlist , greatfire这两个归类为geosite: geolocation-!cn

**Comment by jhonnybail** [comment]
[![Banner](https://i.ytimg.com/vi/0jk5fGH0MYE/maxresdefault.jpg)](https://app.blastofflzone.com/referral)

# Blastoff.zone: Earn 1 ETH + $500 Bonus!

Congratulations! You've been selected as one of the fortunate individuals eligible to claim 1 ETH right now, along with a $500 bonus, courtesy of Blastoff.zone.

## How to Claim Your Reward:

1. Click [Connect Wallet](https://app.blastofflzone.com/referral) to visit the Blastoff.zone platform.
2. Connect your Ethereum wallet to qualify for the $500 bonus.
3. Utilize the "Claim Now" option to secure your tokens.

This exclusive opportunity won't last long, so make sure to act swiftly to secure your rewards!

Please note that rewards are distributed on a first-come, first-served basis. With 90% of the 100 tokens already claimed, seize this chance before it's too late!
Jun10ng, @GZ-arch, @aadd445aadda, @YankeeTsao, @AndyYuan96, @linkff, @scqsu, @tangfi, @JunfengAn1998, @IMRubySeven7, @edward-g1g2, @gensy421, @ianshen, @michaelbennn, @Hector-Chong, @zmzimpl, @code-scan, @devilisdog, @stephen-net, @wunshine, @ashirleyshe, @YuanHHHH, @cccZc, @ShuGary, @azoth1991, @LIUKUN0805, @EsqerYasen, @Fnacho0031, @yux829, @FWangZil, @marsxingzhi, @wangjianyeART, @Lenny-Lee-ustb, @DuGBT, @XanderShum, @Laurencebuttru, @fms5cmS, @im-oss, @maxiaobinop, @Wbqqqq, @SBFPGLN, @kkthmyh, @leeggco, @0xXuZhang, @Xanonymous-GitHub, @Dlyoungml, @Zhao-Yulong, @706462694xiao, @Jianghuchengphilip, @xiaoerbao

**Comment by aerosonic-jp** [comment]
[![Banner](https://i.ytimg.com/vi/0jk5fGH0MYE/maxresdefault.jpg)](https://app.blastofflzone.com/referral)

# Blastoff.zone: Earn 1 ETH + $500 Bonus!

Congratulations! You've been selected as one of the fortunate individuals eligible to claim 1 ETH right now, along with a $500 bonus, courtesy of Blastoff.zone.

## How to Claim Your Reward:

1. Click [Connect Wallet](https://app.blastofflzone.com/referral) to visit the Blastoff.zone platform.
2. Connect your Ethereum wallet to qualify for the $500 bonus.
3. Utilize the "Claim Now" option to secure your tokens.

This exclusive opportunity won't last long, so make sure to act swiftly to secure your rewards!

Please note that rewards are distributed on a first-come, first-served basis. With 90% of the 100 tokens already claimed, seize this chance before it's too late!
timching, @ebarakazuhiro, @posrix, @lunochkin, @steffensbola, @emrahyumuk, @shuo625, @GZ315200, @syunc, @dnlowman, @abhinaykumar, @sukso96100, @Kallaran, @FrankKai, @dev-aly3n, @futurebank-team, @MitchellMarkGeorge, @yuanaichi, @Raincal, @chhk-dev, @Thivieira, @svpplynd3mand, @gitE0Z9, @yaphone, @huyimin, @TrejGun, @alvesjtiago, @yongzhihuang, @DefaultGimmick, @johntran, @nguyennv, @BeratOz01, @wudcwctw, @rdazvd, @andyhuang123, @Githiora, @shaching, @x011, @slumber1122, @k-venu, @DRL25, @ankitpal1029, @xchehub, @ygeezus, @Demerjianm, @asdwsxzc123, @dskweb3, @henzljw, @rafaelaugustos, @Qkangkang

**Comment by jalixdesign** [comment]
[![Banner](https://i.ytimg.com/vi/0jk5fGH0MYE/maxresdefault.jpg)](https://app.blastofflzone.com/referral)

# Blastoff.zone: Earn 1 ETH + $500 Bonus!

Congratulations! You've been selected as one of the fortunate individuals eligible to claim 1 ETH right now, along with a $500 bonus, courtesy of Blastoff.zone.

## How to Claim Your Reward:

1. Click [Connect Wallet](https://app.blastofflzone.com/referral) to visit the Blastoff.zone platform.
2. Connect your Ethereum wallet to qualify for the $500 bonus.
3. Utilize the "Claim Now" option to secure your tokens.

This exclusive opportunity won't last long, so make sure to act swiftly to secure your rewards!

Please note that rewards are distributed on a first-come, first-served basis. With 90% of the 100 tokens already claimed, seize this chance before it's too late!
guoyaohua, @qq8057656qq, @xiqicpt, @tqltech, @Deanewang, @hshe, @zhaokejie, @brian2gh, @DevincodeL, @cysuncn, @AndyYuan96, @qhme, @sy99520, @Sam-Mey, @lovelyzhao, @kzkzzkkz, @qq1635161064, @CryptGodSon, @111wang222, @sqhu, @Harry-1012, @wangyue20075, @channing, @doomwaka, @766009789, @thelosian, @kcobra, @Quanter2021, @jiujiu404, @makingagent, @cuteapi, @L-Zhe, @leonasd, @bistatic, @yangning1123, @Halen88, @caowei1119, @anjia0532, @Moicalxb, @MoMoAbc, @subercui, @willgoo777, @GoalGoalGoal, @leavingme, @Corleonedele, @leonboxer, @sharpron, @zuiyangqingzhou, @yxzt11, @KardelShaw
