### ISSUE TITLE
为什么www.gstatic.com包含在geosite:cn里

### ISSUE THREAD

**Issue by terrason** [Loyalsoldier/domain-list-custom#52]
为什么www.gstatic.com包含在geosite:cn里

**Comment by Loyalsoldier** [comment]
在中国大陆有接入点

**Comment by ihidao** [comment]
ERROR[0015] [1808331400 5.0s] connection: open connection to www.gstatic.com:443 using outbound/direct[bypass]: dial tcp 142.250.197.67:443: i/o timeout
ERROR[0019] [505451692 5.0s] connection: open connection to fonts.gstatic.com:443 using outbound/direct[bypass]: dial tcp 142.250.71.163:443: i/o timeout
建议设置为代理，我这移动直连不上...
