### ISSUE TITLE
关于@ads的疑惑

### ISSUE THREAD

**Issue by cancanneednews** [Loyalsoldier/domain-list-custom#62]
图片中的category-ads-all 的txt中 有的域名带了 @ 的attr 有的没有，这种会不会影响到域名分流
![图片](https://github.com/Loyalsoldier/domain-list-custom/assets/134935370/7723343e-5997-425d-9ee9-00218dfa1094)

**Comment by Loyalsoldier** [comment]
不是因为 `@ads` 的缘故。

本仓库发布的 `geosite.dat` 文件不同于 https://github.com/Loyalsoldier/v2ray-rules-dat 发布的 `geosite.dat` 文件。

本仓库的 `geosite.dat` 包含 https://github.com/v2fly/domain-list-community 中的所有内容，只是略有更改，见本仓库 README。

而 v2ray-rules-dat 发布的 `geosite.dat` 文件的 `geosite:category-ads-all` 列表中的域名来源于第三方，不包含 https://github.com/v2fly/domain-list-community 项目中 `geosite:category-ads-all` 的域名 / 规则。如果要拦截 https://github.com/v2fly/domain-list-community 项目中的广告域名，请使用 `geosite:category-ads`。

**Comment by Loyalsoldier** [comment]
本仓库中的 txt 文件只用于展示该列表包含的内容，不适合用于路由规则。
