### ISSUE TITLE
cn、geolocation-cn、geolocation-!cn以及@cn 、@!cn 属性的疑问

### ISSUE THREAD

**Issue by lonble** [Loyalsoldier/domain-list-custom#88]
根据README
> - 去除 `cn` 列表里带有 `@ads`、`@!cn` 属性的规则
> - 去除 `geolocation-cn` 列表里带有 `@ads`、`@!cn` 属性的规则
> - 去除 `geolocation-!cn` 列表里带有 `@ads`、`@cn` 属性的规则

那么原来`geolocation-cn@!cn`里的域名怎么表示，比如`icbc.eu`？
同理原来`geolocation-!cn@cn`里的域名怎么表示，比如`apple.cn`和`google.cn`？

**Comment by lonble** [comment]
v2fly的domain-list-community的`cn`是`tld-cn`加上`geolocation-cn`，我在release分支的cn.txt文件里发现这个仓库不是这样。好像所有带`@cn` 属性的域名都在`cn`里？

**Comment by lonble** [comment]
另外我发现`geolocation-cn@!cn`里的域名似乎是加到`geolocation-!cn`里了，测了几个域名都是这样，但不确定。

**Comment by lonble** [comment]
综上，这3个列表的关系不完全像README描述的那样，希望能更新一下描述。也希望解答一下我上面提到的问题。

**Comment by lonble** [comment]
从这三个列表删掉的带`@ads`属性的域名都分到`category-ads-all`了吗？这样是不是有些强制配合广告规则了，我更倾向于用专门的软件去广告。ads与geolocation其实不存在语义冲突。

**Comment by Loyalsoldier** [comment]
全对。

P.S. 计划对本项目进行重构，所以不打算做小修小改，但重构时间表未定。
